### ISSUE TITLE
Installation succeeded but failed to run

### ISSUE THREAD

**Issue by ShawnCHENGRH** [peteboyd/lammps_interface#25]
Dear Pete,

It was a amazing work for those who need to write *.data files. And Thank you for your selfless sharing.

Recently, I tried to generate the data file of IRMOF-1 with your code. However, after a successful installation, I ran the code with an error as shown in the following figure. Could you tell me what caused this problem?

I am looking forward to your reply.

Cheng
China-EU Institute for Clean and Renewable Energy at Huazhong University of Science & Technology 
Email:chengruihuan@hust.edu.cn

![image](https://user-images.githubusercontent.com/50262045/69538802-0fb5d880-0fbe-11ea-8037-9132b74c81c5.png)

**Comment by peteboyd** [comment]
Hi Cheng,
Hard to say but I suspect it has something to do with the version of networkx you are using. This might be related to issue #24. I will, when I get a free moment, make the code forward compatible but in the meantime you might want to use a version of networkx <= 2.3.

It also appears you are running an anaconda prompt from a windows machine. I've only ever tested the code on linux/unix based operating systems and so you might experience problems with your current setup that I cannot fix.

**Comment by peteboyd** [comment]
Possibly fixed with commit 371d5d93110b349d51b5d7bfb7ef2bcc89752b7b

**Comment by ShawnCHENGRH** [comment]
Hi Pete,

I have successfully installed lammps interface in the Linux system interface and checked the version of NetWorx with version 1.11, and then used the IRMOF-1.cif file you provided , but it still failed to run successfully. The error showed in the second figure, do you have any good solutions?

Looking forward to your reply.

Cheng
China-EU Institute for Clean and Renewable Energy at Huazhong University of Science & Technology
Email:chengruihuan@hust.edu.cn

**Comment by ShawnCHENGRH** [comment]
Hi Pete,
I have successfully installed lammps interface in the Linux system interface and checked the version of NetWorx with version 1.11, and then used the IRMOF-1.cif file you provided , but it still failed to run successfully. The error showed in the second figure, do you have any good solutions?
Looking forward to your reply.
Cheng
China-EU Institute for Clean and Renewable Energy at Huazhong University of Science & Technology
Email:chengruihuan@hust.edu.cn

**Comment by ShawnCHENGRH** [comment]
Hi Pete,
I have successfully installed lammps interface in the Linux system interface and checked the version of NetWorx with version 1.11, and then used the IRMOF-1.cif file you provided , but it still failed to run successfully. The error showed in the second figure, do you have any good solutions?
Looking forward to your reply.
Cheng
China-EU Institute for Clean and Renewable Energy at Huazhong University of Science & Technology
Email:chengruihuan@hust.edu.cn

**Comment by ShawnCHENGRH** [comment]
Hi Pete,

I have successfully installed lammps interface in the Linux system interface and checked the version of NetWorx with version 1.11, and then used the IRMOF-1.cif file you provided , but it still failed to run successfully. The error showed in the second figure, do you have any good solutions?

Looking forward to your reply.

Cheng
China-EU Institute for Clean and Renewable Energy at Huazhong University of Science & Technology
Email:chengruihuan@hust.edu.cn
![1](https://user-images.githubusercontent.com/50262045/69902701-9f4af500-13cb-11ea-943c-b749266cc22b.jpg)
![2](https://user-images.githubusercontent.com/50262045/69902704-a4a83f80-13cb-11ea-9a1c-94cc7e408e23.jpg)

**Comment by peteboyd** [comment]
Hi Cheng, I’ve updated the code to work with networkx 2.3+
I think you will have to try with the latest version of networkx (2.4 i think)
you will also have to reinstall the latest release of lammps interface (v 0.1.2)

**Comment by ShawnCHENGRH** [comment]
Hi Pete, I have successfully run the program and built the data file of IRMOF-1 according to your instructions. Next, I will test the files other than the CIF you provided . Thank you again for your selfless sharing and timely reply.
